FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    cmake \
    g++ \
    git \
    libasio-dev \
    libtinyxml2-dev \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/eProsima/Micro-XRCE-DDS-Agent.git /agent \
    && cd /agent \
    && mkdir build && cd build \
    && cmake .. \
    && make -j$(nproc) \
    && make install \
    && ldconfig /usr/local/lib/

CMD ["MicroXRCEAgent", "udp4", "-p", "8888"]